version: 2.1
    
jobs:
  build:
    docker:
      - image: cimg/node:16.6.2
    steps:
      - checkout
      - run:
          working_directory: ~/project/units
          name: Install Dependencies
          command: npm ci
      - run:
          working_directory: ~/project/units
          name: Run Tests
          command: npm test
  
  